site_name: Apuntes DAW
site_description: Apuntes de los módulos del CFGS Desarrollo de Aplicaciones Web
site_author: Arba

site_url: https://codigoronin.github.io/apuntes-daw/
repo_url: https://github.com/codigoronin/apuntes-daw

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details

nav:
  - Inicio: index.md
  - Bases de Datos (0484):
      - "Portada del módulo": bases-de-datos/index.md
      - "UD0 · Presentación del módulo": bases-de-datos/ud0-presentacion.md
      - "UD1 · Almacenamiento, SGBD y el valor del dato": bases-de-datos/ud1-almacenamiento-sgbd-valor-del-dato.md
      - "UD2 · Modelo entidad-relación": bases-de-datos/ud2-modelo-entidad-relacion.md
      - "UD3 · Modelo relacional y normalización": bases-de-datos/ud3-modelo-relacional-normalizacion.md
      - "UD4 · Consultas de datos con SQL": bases-de-datos/ud4-consultas-sql.md
  - Desarrollo Web en Entorno Servidor (0613):
      - "Portada del módulo": desarrollo-web-en-entorno-servidor/index.md
      - "UD0 · Presentación del módulo": desarrollo-web-en-entorno-servidor/ud0-presentacion.md
      - "UD1 · Arquitecturas y tecnologías de programación en servidor": desarrollo-web-en-entorno-servidor/ud1-arquitecturas-tecnologias-servidor.md
      - "UD2 · Código embebido en lenguajes de marcas: sintaxis, estructuras, funciones y formularios": desarrollo-web-en-entorno-servidor/ud2-codigo-embebido-php.md
  - Big Data e Inteligencia Artificial (AOP1089):
      - "Portada del módulo": big-data-e-inteligencia-artificial/index.md
      - "UD0 · Presentación del módulo": big-data-e-inteligencia-artificial/ud0-presentacion.md
      - "UD1 · Python para datos e IA: lenguaje especializado, entorno y librerías": big-data-e-inteligencia-artificial/ud1-python-datos-ia.md
 # - Proyecto Intermodular (0616):
 #     - "Portada del módulo": proyecto-intermodular/index.md
 #     - "Presentación del módulo": proyecto-intermodular/presentacion.md
 #     - "Plantilla de anteproyecto (H1)": proyecto-intermodular/plantilla-anteproyecto.md
  - Recursos:
      - "Entorno de trabajo: VS Code para PHP": recursos/entorno-vscode-php.md
      - "Guía rápida de draw.io": recursos/guia-drawio.md
      - "Estándar de estilo SQL": recursos/estandar-estilo-sql.md
